[package]
name = "bfstool"
version = "1.0.1"
edition = "2021"
authors = ["xNyaDev <xnyadev@pm.me>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/xNyaDev/bfstool/"
homepage = "https://github.com/xNyaDev/bfstool/"
description = "A tool for BFS (Bugbear File System) archives"
categories = ["command-line-utilities"]
keywords = ["bugbear", "bfs", "archive"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitreader = "0.3.6"
clap = { version = "3.2.17", features = ["derive"] }
crc = "3.0.0"
flate2 = "1.0.24"
globset = "0.4.9"
indicatif = "0.17.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
tabled = "0.8.0"

[build-dependencies]
pulldown-cmark = { version = "0.9.2", default-features = false }
serde = { version = "1.0.143", features = ["derive"] }
serde-xml-rs = "0.5.1"
serde_json = "1.0.83"
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "bfstool.exe"
FileDescription = "A tool for BFS (Bugbear File System) archives"
LegalCopyright = "Copyright © xNyaDev 2022"
